theme = "gruvbox_dark_hard"

[editor]
rulers = [120]
color-modes = true
text-width = 120

[editor.indent-guides]
render = true

[editor.statusline]
center = ["mode"]

[editor.whitespace.render]
tab = "all"

[keys.insert]
j = {k = "normal_mode"} # Maps `jk` to exit insert mode

[keys.normal]
C-s = ":w"
g = {a = "code_action"}
"ret" = ["open_below", "normal_mode"] # Maps the enter key to open_below then re-enter normal mode
