excludes = ["*.lock", ".gitignore", "**/*.prettierrc"]

[formatter.fish_indent]
command = "fish_indent-wrapper"
excludes = []
includes = ["*.fish"]
options = []

[formatter.nixfmt-rfc-style]
command = "nixfmt"
includes = ["*.nix"]

[formatter.shfmt]
command = "shfmt"
excludes = []
includes = ["*.sh", "*.bash", "*.envrc", "*.envrc.*"]
options = ["-i", "2", "-s", "-w"]

[formatter.stylua]
command = "stylua"
excludes = []
includes = ["*.lua"]
options = []

[formatter.toml-sort]
command = "toml-sort"
excludes = []
includes = ["*.toml"]
options = ["-i"]
