#!/bin/sh

createToml() {
  # Output the VSCode version
  echo 'vscode_version = "'$(code --version | head -n1)'"'
  echo

  # Loop through each installed extension
  code --list-extensions | while read extension; do
    publisher_name=$(echo "$extension" | cut -d '.' -f 1)
    extension_name=$(echo "$extension" | cut -d '.' -f 2-)
    echo '[[extensions]]'
    echo 'publisher_name = "'$publisher_name'"'
    echo 'extension_name = "'$extension_name'"'
    echo
  done
}

tempFile="temp.toml"
resultFile=${1:-"result.nix"}
echo "Getting list of code extensions..."
createToml > "$tempFile"
if [[ "$resultFile" == "test" ]]; then
  echo "Testing - printed out ${tempFile}."
  exit 0
fi

if [[ ! "$resultFile" == *".nix" ]]; then
  echo "File must end with '.nix'. Usage: ./create <file>.nix or ./create."
  exit 1
fi
echo "Converting to ${resultFile}..."
./nix4vscode "$tempFile" > "$resultFile"
rm "$tempFile"
echo "Done."
