excludes = ["*.lock"]

[formatter.fish_indent]
command = "fish_indent-wrapper"
excludes = []
includes = ["*.fish"]
options = []

[formatter.nixfmt-rfc-style]
command = "nixfmt"
includes = ["*.nix"]

[formatter.shfmt]
command = "shfmt"
excludes = []
includes = ["*.sh", "*.bash", "*.envrc", "*.envrc.*"]
options = ["-i", "2", "-s", "-w"]

[formatter.stylua]
command = "stylua"
excludes = []
includes = ["*.lua"]
options = []

[formatter.toml-sort]
command = "toml-sort"
excludes = []
includes = ["*.toml"]
options = ["-i"]

[formatter.prettier]
command = "prettier"
excludes = []
includes = [
    "*.cjs",
    "*.css",
    "*.html",
    "*.js",
    "*.json",
    "*.json5",
    "*.jsx",
    "*.md",
    "*.mdx",
    "*.mjs",
    "*.scss",
    "*.ts",
    "*.tsx",
    "*.vue",
    "*.yaml",
    "*.yml",
]
options = ["--write"]

[formatter.rustfmt]
command = "rustfmt"
excludes = []
includes = ["*.rs"]
