excludes = ["*.lock", ".gitignore", ".*rc", ".direnv/*", "*.png", "node_modules/*"]

[formatter.gofmt]
command = "gofmt"
excludes = []
includes = ["*.go"]
options = ["-w"]

[formatter.nixfmt-rfc-style]
command = "nixfmt"
includes = ["*.nix"]
